### ISSUE TITLE
Hi, when I call the Flex component it always throws that error

### ISSUE THREAD

**Issue by jairorudas** [nathanstitt/boxible#1]
`./node_modules/boxible/dist/index.module.js
Module not found: Can't resolve '@emotion/styled' in 'S:\Personal Documents\PATH\PROJECT_PATH\node_modules\boxible\dist'`

Can you help me ?

Thanks and regards!

**Comment by nathanstitt** [comment]
yes, that's because `@emotion/styled` is declared as a peer dependency, meaning NPM will not install it for you, instead it'll use the version you already are using in your project.    However I think I'll probably move to normal depends in the next version.  For now you'll have to `nom install @emotion/styled` though

**Comment by jairorudas** [comment]
Right! Tank you!
